### PR TITLE
Implement floor operator

### PR DESCRIPTION
**Pull request by joshuak94**
Call wiggletools floor <input> to take the floor of each number.

### CODE REVIEW

**Comment by joshuak94** [comment]
One thought I had was whether we should be using the floor operator at all. From what I remember, calling floor() can actually get quite expensive for so many repetitions. All we really need is something like a "getOnes" function:

```cpp
wi->value = (data->iter->value == 1 ? 1 : 0);
```

Of course, we could implement this alongside the floor function.

Alternatively, it could be similar to scale, and call it keep. Then it would be called for example `wiggletools keep 1 input.wig` to keep all occurrences of 1s and set the rest to 0. But I'm not sure if something like this would have a use case outside of our own.

**Comment by dzerbino** [comment]
Looks good, but could you please add a test for floor?

**Comment by joshuak94** [comment]
@dzerbino I'm a bit confused regarding the tests. Are they mostly just sanity checks? It seems most of the tests don't actually confirm that the values are correct. Is it enough if I just added
`assert test('../bin/wiggletools do floor fixedStep.wig') == 0)`

**Comment by joshuak94** [comment]
Actually, it looks like one of the tests currently fails. 
`assert test('../bin/wiggletools do isZero diff bam.bam cram.cram') == 0` only passes with == 1 instead.

**Comment by joshuak94** [comment]
Seems to have something to do with this issue: https://github.com/samtools/samtools/issues/857

**Comment by dzerbino** [comment]
Odd, it works for me...

**Pull request merged**
